# Dependency versions
set(GLFW_VERSION "3.4")
set(GLM_VERSION "1.0.1")
set(GLAD_VERSION "2.0.8")
set(IMGUI_VERSION "1.90.8")
set(NLOHMANN_JSON_VERSION "3.11.3")

# Project version
set(CODE2LOGIC_VERSION_MAJOR 1)
set(CODE2LOGIC_VERSION_MINOR 0)
set(CODE2LOGIC_VERSION_PATCH 0)
set(CODE2LOGIC_VERSION "${CODE2LOGIC_VERSION_MAJOR}.${CODE2LOGIC_VERSION_MINOR}.${CODE2LOGIC_VERSION_PATCH}")